{% set name = "qt-command-palette" %}
{% set version = "0.0.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/qt_command_palette-{{ version }}.tar.gz
  sha256: 9935634a63034d5940876132abe5a111f46018fb86e6f0fe1a438e6cc5f7ad3d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - hatchling
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - qtpy >=2.0.0

test:
  imports:
    - qt_command_palette
  commands:
    - pip list
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/qt-command-palette
  summary: A command palette widget for Qt applications
  license: MIT
  license_file: LICENSE.txt
  dev_url: https://github.com/hanjinliu/qt-command-palette

extra:
  recipe-maintainers:
    - goanpeca
    - hanjinlu
